name: Notify

on:
  discussion:
    types: [created, reopened]
  issues:
    types: [opened, reopened]

jobs:
  notify:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 # v5.1.0
      - name: Send notification
        uses: ./
        with:
          bot-token: ${{ secrets.TG_BOT_TOKEN }}
          chat-id: ${{ secrets.TG_CHAT_ID }}
